// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl8SI9znTEKEiM8PdIg0gNjymCf2MXHyo',
    appId: '1:597345318726:web:9904877cb9ad022259d747',
    messagingSenderId: '597345318726',
    projectId: 'inventory-application-57275',
    authDomain: 'inventory-application-57275.firebaseapp.com',
    storageBucket: 'inventory-application-57275.appspot.com',
    measurementId: 'G-P0N89LBKJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ8xBnN35u6fuR66OOsh0acGaJCJmRJps',
    appId: '1:597345318726:android:c548e9d8fa87e57259d747',
    messagingSenderId: '597345318726',
    projectId: 'inventory-application-57275',
    storageBucket: 'inventory-application-57275.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_HA8jhqiFQdcbNjIzuQkaZ07nSKlz0H8',
    appId: '1:597345318726:ios:a8b3d6f8418c9f7a59d747',
    messagingSenderId: '597345318726',
    projectId: 'inventory-application-57275',
    storageBucket: 'inventory-application-57275.appspot.com',
    iosClientId: '597345318726-lhv10hhahin30riu68f2nqk693313r6f.apps.googleusercontent.com',
    iosBundleId: 'com.akive.app',
  );
}
